/** Node-only entrypoint. Never imported by the Bun desktop process. */
import { spawn } from "node:child_process";
import { readFile, writeFile, realpath } from "node:fs/promises";
import { dirname, isAbsolute, relative, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { z } from "zod";
import { bundleWorkflowCode, NativeConnection, Worker, Runtime, DefaultLogger } from "@temporalio/worker";
import { Context } from "@temporalio/activity";
import { ApplicationFailure } from "@temporalio/common";
import { digest, workflowFingerprint } from "./storage.js";
import { stopChild, isAlive } from "./processes.js";
import type { ActivityRequest } from "./workflow.js";

const configuration = z.strictObject({
  mode: z.enum(["bundle", "worker", "service"]), parent: z.number().int().positive(),
  entry: z.string().optional(), packageDirectory: z.string().optional(), destination: z.string().optional(),
  address: z.string().optional(), taskQueue: z.string().optional(), bundle: z.string().optional(),
  bridge: z.string().optional(), token: z.string().optional(), temporalPath: z.string().optional(),
  hostCapability: z.boolean().optional(),
  port: z.number().optional(), database: z.string().optional(),
}).parse(JSON.parse(await readFile(process.argv[2]!, "utf8")));
let shutdown: () => Promise<void> = async () => { process.exit(0); };
const watchdog = setInterval(() => { if (!isAlive(configuration.parent)) void shutdown(); }, 1000);
watchdog.unref();
process.once("SIGTERM", () => void shutdown());
process.once("SIGINT", () => void shutdown());
Runtime.install({ logger: new DefaultLogger("ERROR", () => {}) });
if (configuration.mode === "service") {
  const child = spawn(configuration.temporalPath!, ["server", "start-dev", "--headless", "--ip", "127.0.0.1", "--port", String(configuration.port), "--db-filename", configuration.database!, "--sqlite-pragma", "journal_mode=WAL", "--sqlite-pragma", "synchronous=FULL"], { stdio: ["ignore", "ignore", "pipe"] });
  shutdown = async () => { await stopChild(child); process.exit(0); };
  child.stderr.on("data", () => {});
  child.once("error", () => process.exit(1));
  child.once("exit", (code) => process.exit(code ?? 1));
  await new Promise<void>((resolve) => child.once("exit", () => resolve()));
} else if (configuration.mode === "bundle") {
  const destination = configuration.destination!;
  const entry = join(await realpath(dirname(destination)), "entry.cjs");
  const runtime = fileURLToPath(new URL("./workflow.js", import.meta.url));
  // Generated loader has no package/business data. Package imports remain trusted code.
  await writeFile(entry, `const { executeWorkflow } = require(${JSON.stringify(runtime)}); const registry = require(${JSON.stringify(configuration.entry)}).default; exports.drawloomWorkflow = (start) => executeWorkflow(registry, start);`);
  const packageRoot = await realpath(configuration.packageDirectory!);
  const runtimeRoot = await realpath(dirname(runtime));
  const inside = (root: string, path: string) => { const rel = relative(root, path); return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel)); };
  const dependencies = new Map<string, string>();
  const bundle = await bundleWorkflowCode({
    workflowsPath: entry,
    logger: new DefaultLogger("ERROR", (entry) => console.error(entry.message)),
    webpackConfigHook: (config) => {
      config.resolve ??= {};
      config.resolve.modules = [...(config.resolve.modules ?? ["node_modules"]), dirname(dirname(dirname(createRequire(import.meta.url).resolve("@temporalio/workflow/package.json"))))];
      config.plugins ??= [];
      config.plugins.push({ apply(compiler) {
        compiler.hooks.afterCompile.tap("DrawloomCompleteDependencyClosure", (compilation) => {
          if (compilation.warnings.some((warning) => /critical dependency/i.test(warning.message))) throw new Error("Workflow bundle has unresolved dependency warnings; package self-contained deterministic JavaScript");
        });
        compiler.hooks.compilation.tap("DrawloomContainedWorkflow", (compilation) => {
          compilation.hooks.finishModules.tapPromise("DrawloomContainedWorkflow", async (modules) => {
            for (const module of modules) {
              const resource = Reflect.get(module, "resource") as unknown;
              if (typeof resource !== "string" || resource.includes("?")) continue;
              // Temporal's generated Webpack virtual entry has no file on disk.
              if (resource === entry.replace(/\.[^.]+$/, "-autogenerated-entrypoint.cjs")) continue;
              const path = await realpath(resource);
              const generated = path === entry || path.startsWith(`${entry}-`);
              // Only the package, provider runtime, Temporal runtime and portable public dependencies.
              const dependency = /[/\\]node_modules[/\\](?:\.bun[/\\][^/\\]+[/\\]node_modules[/\\])?(?:@temporalio[/\\]|@drawloom[/\\](?:orchestration|agent|tools|context|host)[/\\]|@modelcontextprotocol[/\\]sdk[/\\]|zod[/\\]|long[/\\]|ms[/\\]|protobufjs[/\\]|@protobufjs[/\\]|uuid[/\\]|abort-controller[/\\]|event-target-shim[/\\]|nexus-rpc[/\\])/.test(path);
              const publicContract = /[/\\]packages[/\\](?:orchestration[/\\]orchestration|agent[/\\]agent|tools[/\\]tools|context[/\\]context|host[/\\]host)[/\\]dist[/\\]/.test(path);
              const hostKnowledgeContract = configuration.hostCapability === true && (/[/\\]packages[/\\]knowledge[/\\]knowledge[/\\]dist[/\\]/.test(path) || /[/\\]node_modules[/\\](?:\.bun[/\\][^/\\]+[/\\]node_modules[/\\])?@drawloom[/\\]knowledge[/\\]/.test(path));
              if (!generated && !inside(packageRoot, path) && !inside(runtimeRoot, path) && !dependency && !publicContract && !hostKnowledgeContract)
                throw new Error(`Workflow dependency containment rejected: ${path}`);
              dependencies.set(path, digest(await readFile(path)));
            }
          });
        });
      } });
      return config;
    },
  });
  const fingerprint = workflowFingerprint(bundle.code, [...dependencies]);
  await writeFile(destination, bundle.code, { mode: 0o600 });
  console.log(JSON.stringify({ fingerprint, dependencies: [...dependencies] }));
} else {
  const connection = await NativeConnection.connect({ address: configuration.address! });
  const Response = z.union([z.strictObject({ value: z.json() }), z.strictObject({ error: z.string(), code: z.enum(["retryable", "denied", "invalid", "unknown"]) })]);
  async function call(path: string, body: unknown, attempt = 1): Promise<unknown> {
    let data;
    try {
      const response = await fetch(`${configuration.bridge}${path}`, { method: "POST", headers: { authorization: `Bearer ${configuration.token}`, "content-type": "application/json" }, body: JSON.stringify(body), signal: AbortSignal.timeout(86_400_000) });
      if (!response.ok) throw new Error("Bridge unavailable");
      const text = await response.text();
      if (text.length > 1024 * 1024) throw new Error("Bridge result too large");
      data = Response.parse(JSON.parse(text));
    } catch {
      throw ApplicationFailure.create({ message: "Dispatch response unavailable; effect outcome unknown", type: "unknown", nonRetryable: true, details: [attempt] });
    }
    if ("error" in data) throw ApplicationFailure.create({ message: data.error, type: data.code, nonRetryable: data.code !== "retryable", details: [attempt] });
    return data.value;
  }
  const worker = await Worker.create({
    connection, taskQueue: configuration.taskQueue!, workflowBundle: { codePath: configuration.bundle! },
    shutdownGraceTime: "2 seconds", shutdownForceTime: "5 seconds",
    maxConcurrentActivityTaskExecutions: 32,
    activities: {
      async dispatch(request: ActivityRequest) {
        const context = Context.current();
        const timer = setInterval(() => context.heartbeat(), 500);
        const cancel = () => { void call("/cancel", { runId: request.runId }).catch(() => {}); };
        context.cancellationSignal.addEventListener("abort", cancel, { once: true });
        try { return { value: await call("/dispatch", { ...request, attempt: context.info.attempt }, context.info.attempt), attempt: context.info.attempt }; }
        finally { clearInterval(timer); context.cancellationSignal.removeEventListener("abort", cancel); }
      },
      cleanup: (runId: string) => call("/cancel", { runId }),
    },
  });
  shutdown = async () => { if (worker.getState() === "RUNNING") worker.shutdown(); };
  const running = worker.run();
  console.log("DRAWLOOM_WORKER_READY");
  try { await running; } finally { await connection.close(); }
}
clearInterval(watchdog);
